// <auto-generated />
using System;
using Inventory.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Service.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260408083711_AddImportReceiptWithSupplier")]
    partial class AddImportReceiptWithSupplier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("Inventory.Service.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện tử"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gia dụng"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thực phẩm"
                        });
                });

            modelBuilder.Entity("Inventory.Service.Models.ExportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExportReceipts");
                });

            modelBuilder.Entity("Inventory.Service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Điện tử",
                            MinStock = 10,
                            Name = "Laptop Dell XPS 15",
                            Stock = 50,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Điện tử",
                            MinStock = 20,
                            Name = "Bàn phím cơ Logitech",
                            Stock = 120,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Gia dụng",
                            MinStock = 5,
                            Name = "Nồi chiên không dầu",
                            Stock = 30,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Thực phẩm",
                            MinStock = 50,
                            Name = "Nước mắm Nam Ngư",
                            Stock = 500,
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Điện tử",
                            MinStock = 15,
                            Name = "Chuột không dây Microsoft",
                            Stock = 85,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Điện tử",
                            MinStock = 8,
                            Name = "Tai nghe Sony WH-CH520",
                            Stock = 40,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Điện tử",
                            MinStock = 12,
                            Name = "Sạc dự phòng Anker 20000mAh",
                            Stock = 65,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Gia dụng",
                            MinStock = 10,
                            Name = "Ấm siêu tốc Philips",
                            Stock = 55,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Gia dụng",
                            MinStock = 5,
                            Name = "Máy hút bụi cầm tay",
                            Stock = 22,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Gia dụng",
                            MinStock = 8,
                            Name = "Nồi cơm điện Sharp",
                            Stock = 48,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Gia dụng",
                            MinStock = 25,
                            Name = "Bột giặt OMO 3kg",
                            Stock = 140,
                            Unit = "Gói"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Thực phẩm",
                            MinStock = 40,
                            Name = "Mì ăn liền Hảo Hảo",
                            Stock = 260,
                            Unit = "Thùng"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Thực phẩm",
                            MinStock = 30,
                            Name = "Gạo ST25",
                            Stock = 180,
                            Unit = "Bao"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Thực phẩm",
                            MinStock = 35,
                            Name = "Dầu ăn Neptune",
                            Stock = 210,
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Thực phẩm",
                            MinStock = 60,
                            Name = "Sữa tươi Vinamilk",
                            Stock = 320,
                            Unit = "Lốc"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Thực phẩm",
                            MinStock = 25,
                            Name = "Đường Biên Hòa",
                            Stock = 175,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Gia dụng",
                            MinStock = 20,
                            Name = "Nước rửa chén Sunlight",
                            Stock = 110,
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Điện tử",
                            MinStock = 18,
                            Name = "Bóng đèn LED Rạng Đông",
                            Stock = 95,
                            Unit = "Bóng"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Điện tử",
                            MinStock = 12,
                            Name = "Ổ cắm điện Lioa",
                            Stock = 70,
                            Unit = "Cái"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Gia dụng",
                            MinStock = 40,
                            Name = "Khăn giấy Pulppy",
                            Stock = 240,
                            Unit = "Gói"
                        });
                });

            modelBuilder.Entity("Inventory.Service.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
