version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  authservice:
    build:
      context: ./Auth.Service
    container_name: authservice
    ports:
      - "5002:80"
    depends_on:
      - sqlserver

  inventoryservice:
    build:
      context: ./Inventory.Service
    container_name: inventoryservice
    ports:
      - "5003:80"
    depends_on:
      - sqlserver

  supplierservice:
    build:
      context: ./Supplier.Service
    container_name: supplierservice
    ports:
      - "5004:80"
    depends_on:
      - sqlserver

  reportservice:
    build:
      context: ./Report.Service
    container_name: reportservice
    ports:
      - "5001:80"
    depends_on:
      - sqlserver

  apigateway:
    build:
      context: ./ApiGateway
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - reportservice
      - authservice
      - inventoryservice
      - supplierservice