/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#380d00",
                "secondary-container": "#b6c8fe",
                "on-secondary-container": "#415382",
                "on-background": "#091c35",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#091c35",
                "surface-container": "#e7eeff",
                "surface-container-high": "#dfe8ff",
                "surface-variant": "#d6e3ff",
                "primary-container": "#0052cc",
                "surface-container-highest": "#d6e3ff",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                primary: "#003d9b",
                background: "#f9f9ff",
                "on-tertiary-fixed-variant": "#812800",
                error: "#ba1a1a",
                "surface-dim": "#cadbfc",
                "tertiary-fixed": "#ffdbcf",
                "surface-container-low": "#f0f3ff",
                secondary: "#4c5d8d",
                "on-secondary-fixed": "#021945",
                "on-error": "#ffffff",
                "on-surface-variant": "#434654",
                "on-error-container": "#93000a",
                "on-primary-fixed-variant": "#0040a2",
                "tertiary-container": "#a33500",
                "primary-fixed-dim": "#b2c5ff",
                "secondary-fixed": "#dae2ff",
                "tertiary-fixed-dim": "#ffb59b",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#001848",
                "inverse-surface": "#20314b",
                surface: "#f9f9ff",
                "on-primary": "#ffffff",
                "on-secondary-fixed-variant": "#344573",
                "outline-variant": "#c3c6d6",
                "inverse-on-surface": "#ecf0ff",
                tertiary: "#7b2600",
                "secondary-fixed-dim": "#b4c5fb",
                "inverse-primary": "#b2c5ff",
                "on-tertiary-container": "#ffc6b2",
                outline: "#737685",
                "primary-fixed": "#dae2ff",
                "on-primary-container": "#c4d2ff",
                "surface-bright": "#f9f9ff",
                "surface-tint": "#0c56d0",
            },
            fontFamily: {
                headline: ["Inter"],
                body: ["Inter"],
                label: ["Inter"],
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
};
